services:
    laravel.test:
        env_file:
            - ./.env.sail
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                NODE_VERSION: '25'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './.env.sail:/var/www/html/.env'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'odds'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - './.env.sail:/var/www/html/.env'
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
            - './.env.sail:/var/www/html/.env'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    redisinsight:
        image: redis/redisinsight:latest
        ports:
            - "5540:5540"
        environment:
            RI_ACCEPT_TERMS_AND_CONDITIONS: "true"
            # Один коннект — можно без * и без индекса, будет считаться как id=0 :contentReference[oaicite:1]{index=1}
            RI_REDIS_HOST: "redis"
            RI_REDIS_PORT: "6379"
            RI_REDIS_ALIAS: "local-redis"
            RI_REDIS_DB: "0"
        volumes:
            - sail-redisinsight:/data
            - './.env.sail:/var/www/html/.env'
        depends_on:
            - redis
        networks:
            - sail

    queue:
        image: sail-8.5/app
        depends_on:
            - laravel.test
            - redis
            - mysql
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './.env.sail:/var/www/html/.env'
        networks:
            - sail
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
            LARAVEL_SAIL: '1'
        command: php artisan queue:work
        restart: unless-stopped

    scheduler:
        image: sail-8.5/app
        depends_on:
            - laravel.test
            - redis
            - mysql
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './.env.sail:/var/www/html/.env'
        networks:
            - sail
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '${WWWGROUP}'
            LARAVEL_SAIL: '1'
        command: php artisan schedule:work
        restart: unless-stopped


networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-redisinsight:
        driver: local
